export const GET_LOGGED_USER_REQUESTED = 'GET_LOGGED_USER_REQUESTED';
export const GET_LOGGED_USER_SUCCESS = 'GET_LOGGED_USER_SUCCESS';
export const GET_LOGGED_USER_FAILED = 'GET_LOGGED_USER_FAILED';

export const GET_REQ_SHIFT_REQUESTED = 'GET_REQ_SHIFT_REQUESTED';
export const GET_REQ_SHIFT_SUCCESS = 'GET_REQ_SHIFT_SUCCESS';
export const GET_REQ_SHIFT_FAILED = 'GET_REQ_SHIFT_FAILED';

export const GET_USER_REQ_SHIFT_REQUESTED = 'GET_USER_REQ_SHIFT_REQUESTED';
export const GET_USER_REQ_SHIFT_SUCCESS = 'GET_USER_REQ_SHIFT_SUCCESS';
export const GET_USER_REQ_SHIFT_FAILED = 'GET_USER_REQ_SHIFT_FAILED';

export const ADD_SUB_SHIFT_REQUESTED = 'ADD_SUB_SHIFT_REQUESTED';
export const ADD_SUB_SHIFT_SUCCESS = 'ADD_SUB_SHIFT_SUCCESS';
export const ADD_SUB_SHIFT_FAILED = 'ADD_SUB_SHIFT_FAILED';

// export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED';
// export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
// export const GET_USERS_FAILED = 'GET_USERS_FAILED';

